### ISSUE TITLE
How to run this file?

### ISSUE THREAD

**Issue by chip-04** [Sankalpa-Sarkar/Sign-Language-Recognition-using-PCA#1]
hi, just wondering what I need to do to run this file? I had loaded the PCA-DB file, but there is nothing working

btw thank you for the code
![1](https://user-images.githubusercontent.com/62021238/113702348-f83b4380-970b-11eb-8f6f-75214e97b60f.PNG)

**Comment by Sankalpa-Sarkar** [comment]
The errors that are occurring refer directly to the training and testing datasets. The code cannot find the testing images. Make sure that:

1.  Your training code is in the same folder as the dataset that you are training. 
2. Your testing code is in the same folder as the testing dataset.
3. The PCA-DB.mat file must be copied from the training dataset folder to the testing dataset folder.
